### ISSUE TITLE
Submodule 'frontend'. Host key verification failed. fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by PanasyukVA** [Bandwidth/webrtc-sample-conference-node#16]
Hello
During cloning repo I got the error:

folder path>git clone --recursive https://github.com/Bandwidth/webrtc-sample-conference-node.git
Cloning into 'webrtc-sample-conference-node'...
remote: Enumerating objects: 267, done.
remote: Counting objects: 100% (267/267), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 267 (delta 148), reused 225 (delta 118), pack-reused 0
Receiving objects: 100% (267/267), 14.99 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (148/148), done.
Submodule 'frontend' (git@github.com:Bandwidth/webrtc-sample-conference-frontend
.git) registered for path 'frontend'
Cloning into 'folder path'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Bandwidth/webrtc-sample-conference-frontend.git'
 into submodule path 'folder path/webrtc-samp
le-conference-node/frontend' failed
Failed to clone 'frontend'. Retry scheduled

How can I get this code?

**Comment by jturner-bw** [comment]
If you're able, try cloning --recursive `git@github.com:Bandwidth/webrtc-sample-conference-node.git`. It appears Git prefers to use SSH with submodules.

**Comment by PanasyukVA1** [comment]
Thank you. It works with Git bash and SSH
